In [1]:
# MLP DeepLearning

import torch
from torch import nn

# tensor, 입력데이터가 12이하라면 정답이 0이고 14이상이면 정답이 1이라는 것을 알 수 있음
x_train = torch.Tensor( [2,4,6,8,10,12,14,16,18,20] ).view(10,1) # reshape
y_train = torch.Tensor( [0,0,0,0,0,0,1,1,1,1] ).view(10,1) \

print(x_train.shape, y_train.shape)

torch.Size([10, 1]) torch.Size([10, 1])


In [2]:
# DeepLearning Model
# 입력층 -> 은닉층 -> 출력층
class DeepLearningModel(nn.Module):
    def __init__(self, *args):
        super().__init__()
        self.deeplearning_stack = nn.Sequential(
            nn.Linear(1, 8), # 1개의 입력데이터에 대해서 8개의 출력을 내놓는 은닉층
            nn.Linear(8, 1), # 8개의 입력데이터에 대해서 1개의 출력을 내놓는 출력층
            nn.Sigmoid() # 활성화함수 0~1 사이값 리턴
        )
    
    def forward(self, x):
        x = self.deeplearning_stack(x)
        return x

In [3]:
# Model 객체 생성
model = DeepLearningModel()

# Model 파라미터(가중치, 바이어스) 값 확인
for name, child in model.named_children():
    for param in child.parameters():
        print(name, param)

# 입력층-출력층 가중치 8개(1x8)
# deeplearning_stack Parameter containing:
# tensor([[-0.9416],
#         [-0.0063],
#         [ 0.4107],
#         [ 0.6724],
#         [-0.0693],
#         [-0.0932],
#         [-0.5608],
#         [-0.3111]], requires_grad=True)
# 은닉층 바이어스 8개
# deeplearning_stack Parameter containing:
# tensor([-0.7501,  0.1256, -0.3569,  0.3050,  0.8730,  0.7295,  0.6094, -0.3402],
#        requires_grad=True)

# 은닉층-출력층 가중치 8개(8x1)
# deeplearning_stack Parameter containing:
# tensor([[ 0.0211,  0.2055,  0.3179,  0.0011, -0.2181,  0.2186, -0.0436,  0.3099]],
#        requires_grad=True)
# 출력층 바이어스 1개
# deeplearning_stack Parameter containing:
# tensor([-0.1547], requires_grad=True)

deeplearning_stack Parameter containing:
tensor([[-0.8941],
        [ 0.1179],
        [-0.9428],
        [-0.6148],
        [-0.1327],
        [-0.6939],
        [-0.7274],
        [ 0.7082]], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([ 0.5467, -0.4592, -0.8792, -0.6073, -0.3293, -0.0361, -0.0652,  0.5157],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([[ 0.1783, -0.2244,  0.0507, -0.0163,  0.3268, -0.0215, -0.2577,  0.2859]],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([0.2636], requires_grad=True)


In [4]:
# loss function
loss_function = nn.BCELoss() # loss function 이지 분류이므로 Binary CrossEntropy(BCELoss())

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-1) # 확율적경사하강법 SGD(가장 기본)

In [5]:
# Model 학습
nums_epoch = 5000

for epoch in range(nums_epoch + 1):
    # 예측값 계산
    outputs = model(x_train)

    # 손실함수값 계산
    loss = loss_function(outputs, y_train)

    # 오차역전파
    optimizer.zero_grad() # 미분 초기화
    loss.backward() # 미분 연산
    optimizer.step() # 미분 연산 후 가중치, 바이어스 파라미터 업데이트

    if epoch %100 == 0:
        print('epoch = ', epoch, ', loss = ', loss.item())

epoch =  0 , loss =  1.03118097782135
epoch =  100 , loss =  0.4154469966888428
epoch =  200 , loss =  0.32460787892341614
epoch =  300 , loss =  0.27399080991744995
epoch =  400 , loss =  0.24057264626026154
epoch =  500 , loss =  0.21645545959472656
epoch =  600 , loss =  0.19803719222545624
epoch =  700 , loss =  0.1834041178226471
epoch =  800 , loss =  0.17143328487873077
epoch =  900 , loss =  0.1614156812429428
epoch =  1000 , loss =  0.15287955105304718
epoch =  1100 , loss =  0.14549632370471954
epoch =  1200 , loss =  0.1390308290719986
epoch =  1300 , loss =  0.1333092302083969
epoch =  1400 , loss =  0.1281990110874176
epoch =  1500 , loss =  0.12359970808029175
epoch =  1600 , loss =  0.11943082511425018
epoch =  1700 , loss =  0.11562981456518173
epoch =  1800 , loss =  0.11214442551136017
epoch =  1900 , loss =  0.10893256962299347
epoch =  2000 , loss =  0.10596048831939697
epoch =  2100 , loss =  0.1031985878944397
epoch =  2200 , loss =  0.10062332451343536
epoch =  2

In [6]:
# Model 테스트
model.eval() # 추론 모드 전환

test_data = torch.Tensor( [0.5, 3.0, 3.5, 11.0, 13.0, 31.0] ).view(6, 1)

# 모델 예측
pred = model(test_data)

# 예측값 0.5 이상 True -> 1.0 변환, 0.5 이하 False -> 0.0 변환
logical_value = (pred > 0.5).float()

print(pred)
print(logical_value)

tensor([[8.9543e-14],
        [3.7077e-11],
        [1.2374e-10],
        [8.7088e-03],
        [5.2153e-01],
        [1.0000e+00]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [9]:
# Save the model checkpoint
torch.save(model.state_dict(), '.\\models\\model_mlp.ckpt')