In [ ]:
# MLP DeepLearning

import torch
from torch import nn

# tensor, 입력데이터가 12이하라면 정답이 0이고 14이상이면 정답이 1이라는 것을 알 수 있음
x_train = torch.Tensor( [2,4,6,8,10,12,14,16,18,20] ).view(10,1) # reshape
y_train = torch.Tensor( [0,0,0,0,0,0,1,1,1,1] ).view(10,1) \

print(x_train.shape, y_train.shape)

torch.Size([10, 1]) torch.Size([10, 1])


In [ ]:
# DeepLearning Model
# 입력층 -> 은닉층 -> 출력층
class DeepLearningModel(nn.Module):
    def __init__(self, *args):
        super().__init__()
        self.deeplearning_stack = nn.Sequential(
            nn.Linear(1, 8), # 1개의 입력데이터에 대해서 8개의 출력을 내놓는 은닉층
            nn.Linear(8, 1), # 8개의 입력데이터에 대해서 1개의 출력을 내놓는 출력층
            nn.Sigmoid() # 활성화함수 0~1 사이값 리턴
        )
    
    def forward(self, x):
        x = self.deeplearning_stack(x)
        return x

In [6]:
# Model 객체 생성
model = DeepLearningModel()

# Model 파라미터(가중치, 바이어스) 값 확인
for name, child in model.named_children():
    for param in child.parameters():
        print(name, param)

# 입력층-출력층 가중치 8개(1x8)
# deeplearning_stack Parameter containing:
# tensor([[-0.9416],
#         [-0.0063],
#         [ 0.4107],
#         [ 0.6724],
#         [-0.0693],
#         [-0.0932],
#         [-0.5608],
#         [-0.3111]], requires_grad=True)
# 은닉층 바이어스 8개
# deeplearning_stack Parameter containing:
# tensor([-0.7501,  0.1256, -0.3569,  0.3050,  0.8730,  0.7295,  0.6094, -0.3402],
#        requires_grad=True)

# 은닉층-출력층 가중치 8개(8x1)
# deeplearning_stack Parameter containing:
# tensor([[ 0.0211,  0.2055,  0.3179,  0.0011, -0.2181,  0.2186, -0.0436,  0.3099]],
#        requires_grad=True)
# 출력층 바이어스 1개
# deeplearning_stack Parameter containing:
# tensor([-0.1547], requires_grad=True)

deeplearning_stack Parameter containing:
tensor([[-0.3074],
        [ 0.9485],
        [-0.0775],
        [ 0.6588],
        [ 0.3084],
        [-0.1917],
        [ 0.3418],
        [ 0.2948]], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-0.3860, -0.4853, -0.4499, -0.6149, -0.8236,  0.3415, -0.6960,  0.2016],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([[ 0.0957,  0.0421,  0.0544,  0.0475,  0.0445,  0.0834, -0.2072,  0.1896]],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([0.0597], requires_grad=True)


In [8]:
# loss function
loss_function = nn.BCELoss() # loss function 이지 분류이므로 Binary CrossEntropy(BCELoss())

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-1) # 확율적경사하강법 SGD(가장 기본)

In [10]:
# Model 학습
nums_epoch = 5000

for epoch in range(nums_epoch + 1):
    # 예측값 계산
    outputs = model(x_train)

    # 손실함수값 계산
    loss = loss_function(outputs, y_train)

    # 오차역전파
    optimizer.zero_grad() # 미분 초기화
    loss.backward() # 미분 연산
    optimizer.step() # 미분 연산 후 가중치, 바이어스 파라미터 업데이트

    if epoch %100 == 0:
        print('epoch = ', epoch, ', loss = ', loss.item())

epoch =  0 , loss =  0.18116353452205658
epoch =  100 , loss =  0.1663568913936615
epoch =  200 , loss =  0.15462958812713623
epoch =  300 , loss =  0.1450420618057251
epoch =  400 , loss =  0.13701122999191284
epoch =  500 , loss =  0.13015416264533997
epoch =  600 , loss =  0.12420759350061417
epoch =  700 , loss =  0.11898478120565414
epoch =  800 , loss =  0.11434732377529144
epoch =  900 , loss =  0.11019174009561539
epoch =  1000 , loss =  0.10643782466650009
epoch =  1100 , loss =  0.1030232161283493
epoch =  1200 , loss =  0.09989811480045319
epoch =  1300 , loss =  0.0970214381814003
epoch =  1400 , loss =  0.09436104446649551
epoch =  1500 , loss =  0.09188933670520782
epoch =  1600 , loss =  0.08958306908607483
epoch =  1700 , loss =  0.08742395788431168
epoch =  1800 , loss =  0.08539468795061111
epoch =  1900 , loss =  0.08348260819911957
epoch =  2000 , loss =  0.08167480677366257
epoch =  2100 , loss =  0.07996023446321487
epoch =  2200 , loss =  0.07833444327116013
epoc

In [11]:
# Model 테스트
model.eval() # 추론 모드 전환

test_data = torch.Tensor( [0.5, 3.0, 3.5, 11.0, 13.0, 31.0] ).view(6, 1)

# 모델 예측
pred = model(test_data)

# 예측값 0.5 이상 True -> 1.0 변환, 0.5 이하 False -> 0.0 변환
logical_value = (pred > 0.5).float()

print(pred)
print(logical_value)

tensor([[2.5112e-16],
        [3.3654e-13],
        [1.4206e-12],
        [3.4077e-03],
        [5.2052e-01],
        [1.0000e+00]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])
