In [ ]:
# RNN 개념과 동작원리
# RNN 모델은 인간의 언어나 날씨처럼 시간에 따라서 변하는 시퀀스 데이터를 분석하고 예측하는데 사용되기 때문에, 이러한 RNN 입력 데이터에는
# 반드시 시간(또는 순서) 정보가 포함되어 있어야 함

# 즉 RNN 입력 데이터는 다음과 같이 시간 정보(time steps)가 포함되어 있는 같이 3차원 테서로 만들어서 RNN 모델의 입력 층으로 넣어주는 것이 일반적임
# RNN 입력 데이터 - 시간 정보 time_steps 포함된 3차원 텐서, (batch_size, time_steps, feature_nums)
# batch_size - time_steps 으로 분리되어 있는 데이터의 개숙 총 몇개인지를 나타냄
# time_steps - 몇개의 feature를 모아서 최종 정답을 만들어 내는지를 나타냄. 즉 몇개의 시점(time)을 이용해서 최종 정답을 만들것인지를 정의하는 항목으로 시간 정보를 나타냄
# feature_nums -  하나의 시정(time)에 RNN 모델의 input_layer로 들어가는 데이터 개수, 즉 RNN input layer로 한번에 들어가는 데이터 개수


In [6]:
# RNN 데이터 만들기 위해서는 먼저 
# 1)feature -> 2)time step -> 3)batch 순서로 리스트(list) 입력 데이터를 만들고
# -> 4)time step 개수와 일치하는 정답(label) 리스트(list)를 만든 후에, 입력과 정답데이터를 이용해서 
# -> 5)numpy 또는 TensorDataset 을 생성함

import torch
from torch.utils.data import TensorDataset
import numpy as np
# GPU
DEVICE = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print('pytorch version : ', torch.__version__, ', device : ', DEVICE)

# input data
input_list = [ [ [1,2], [2,3], [3,4] ], [ [5,6], [6,7], [7,8] ] ]
label_list = [10, 20]

# numpy data
x_data = np.array(input_list)
y_data = np.array(label_list)
print(x_data.shape, y_data.shape)

# tensor data
x_data = torch.FloatTensor(input_list)
y_data = torch.FloatTensor(label_list)
print(x_data.shape, y_data.shape)

# TensorDataset
dataset = TensorDataset(x_data, y_data)

pytorch version :  2.7.1+cu118 , device :  cuda
(2, 3, 2) (2,)
torch.Size([2, 3, 2]) torch.Size([2])


In [ ]:
# pytorch RNN API 설명
# torch.nn.RNN(input_size, hidden_size, num_layers, batch_first)
# input_size - RNN input layer로 들어가는 특성(feature) 값의 개수, 즉 feature 개수가 1개라면 input_size=1, feature 개수가 3개라면 input_size=3 으로 입력
# hidden_size - hidden_state 개수, 즉 RNN 레이어 출력 개수를 나타냄, RNN layer 출력 개수가 1개라면 hidden_size=1, RNN layer 출력 개수가 3개라면 hidden_size=3
# num_layers - RNN layer 겹겹이 쌓아올릴 수 있으며 num_layers는 몇개의 RNN layer가 쌓여 있는지를 나타냄, 즉 RNN layer 2개가 쌓여 있으면 num_layers=2(기본은 1)
# batch_first - 입력 받은 데이터의 shape중 첫 번째 차원을 batch로 간주할 것인지를 설정하는데, 일반적으로 pytorch에서 입력데이터는 batch를 첫번째 차원으로 지정하기 때문에 batch_first=True로 설정


In [39]:
# RNN, LSTM, GRU API
input_data = torch.tensor([ [ [1], [2], [3] ] ]).float() # (1, 3, 1) shape을 가지는 입력데이터

# 간단한 RNN, LSTM, GRU 모델
MyRNNModel = torch.nn.RNN(input_size=1, # input 레이어로 들어가는 특성(feature) 개수
                          hidden_size=3, # RNN 출력 개수
                          batch_first=True) # 입력 받은 데이터 shape 중 첫번째 차원을 batch로 간주 여부

# 모델 추론 값
# 첫번째 리턴값 outputs 모든 시점(time steps) hidden state, [h1, h2, h3]
# 두번째 리턴값 last_hs 마지막 시점(time steps) hidden state, [h3]
outputs, last_hs = MyRNNModel(input_data)

print(outputs.shape)
print(outputs)
print('==============================================================================')
print(last_hs.shape)
print(last_hs)

# tensor([[[-0.5678,  0.3293, -0.6016], h1
#         [-0.8632,  0.5324, -0.5242], h2
#         [-0.9531,  0.7018, -0.5318]]], grad_fn=<TransposeBackward1>) h3

# tensor([[[-0.9531,  0.7018, -0.5318]]], grad_fn=<StackBackward0>) h3

torch.Size([1, 3, 3])
tensor([[[-0.2992,  0.0338, -0.2878],
         [-0.3816, -0.0949, -0.1021],
         [-0.2650,  0.1048, -0.1406]]], grad_fn=<TransposeBackward1>)
torch.Size([1, 1, 3])
tensor([[[-0.2650,  0.1048, -0.1406]]], grad_fn=<StackBackward0>)
